raw <- read.table("/data2/bsi/secondary/Radisky_Derek_m025888/config/170821_MayoClinic_RNASeq_NotreDame/v1.2.1.5_SE_trimmed/diff_exp/expressed_allSamples.txt", row.names=1, header=TRUE)
rawlog <- log2(raw+1)
png("/data2/bsi/secondary/Radisky_Derek_m025888/config/170821_MayoClinic_RNASeq_NotreDame/v1.2.1.5_SE_trimmed/diff_exp/CDF_allSamples.png",units="in",width=8,height=8,res=800)
plot(ecdf(rawlog[,1]),col="violetred3", main="Cumulative Distribution of Gene Counts", xlab="log2(raw_counts)", ylab="Proportion of genes")
plot(ecdf(rawlog[,2]),col="royalblue", add=T)
plot(ecdf(rawlog[,3]),col="plum", add=T)
plot(ecdf(rawlog[,4]),col="gold", add=T)
plot(ecdf(rawlog[,5]),col="green", add=T, pch=".")
plot(ecdf(rawlog[,6]),col="tomato", add=T)
legend("topright", c("s_50170","s_53530","s_54038","s_58484","s_59138","s_63601"), fill=c("violetred3","royalblue","plum","gold","green","tomato"))
dev.off()
